document.addEventListener('DOMContentLoaded', () => {
const biaisCognitifs = [
    { nom: "Biais de confirmation", description: "La tendance à rechercher, interpréter, favoriser et se rappeler des informations de manière à confirmer ses propres croyances ou hypothèses.", emoji: "🔍" },
    { nom: "Effet de halo", description: "La tendance à se laisser influencer par une impression générale positive ou négative.", emoji: "😇" },
    { nom: "Biais de négativité", description: "La tendance à accorder plus d'importance aux expériences négatives qu'aux positives.", emoji: "😡" },
    { nom: "Biais d'ancrage", description: "La tendance à se fier trop fortement à la première information rencontrée (l'ancre) lors de la prise de décision.", emoji: "⚓" },
    { nom: "Effet de simple exposition", description: "La tendance à développer une préférence pour les choses simplement parce qu'on y est exposé de manière répétée.", emoji: "👀" },
    { nom: "Biais d'autocomplaisance", description: "La tendance à attribuer ses succès à ses propres qualités et ses échecs à des facteurs externes.", emoji: "😌" },
    { nom: "Biais de disponibilité", description: "La tendance à surévaluer les informations immédiatement disponibles dans la mémoire lorsqu'on évalue une situation.", emoji: "📚" },
    { nom: "Effet de Dunning-Kruger", description: "La tendance des personnes peu compétentes dans un domaine à surestimer leurs compétences.", emoji: "🤔" },
    { nom: "Biais de cadrage", description: "La tendance à être influencé par la manière dont une information est présentée plutôt que par l'information elle-même.", emoji: "🖼️" },
    { nom: "Biais de statu quo", description: "La préférence pour que les choses restent en l'état plutôt que de changer.", emoji: "🔄" },
    { nom: "Biais d'optimisme", description: "La tendance à croire que l'on est moins susceptible de rencontrer des événements négatifs par rapport aux autres.", emoji: "🌞" },
    { nom: "Effet de primauté", description: "La tendance à mieux se souvenir des premières informations reçues.", emoji: "📝" },
    { nom: "Effet de récence", description: "La tendance à mieux se souvenir des informations les plus récentes.", emoji: "⏳" },
    { nom: "Biais de représentativité", description: "La tendance à estimer la probabilité d'un événement en se basant sur la similarité avec un prototype existant dans la mémoire.", emoji: "📊" },
    { nom: "Effet de faux consensus", description: "La tendance à surestimer le degré de consensus autour de ses propres opinions, croyances et comportements.", emoji: "🤝" },
    { nom: "Effet Barnum", description: "La tendance à accepter des descriptions vagues et générales comme s'appliquant spécifiquement à soi-même.", emoji: "🎪" },
    { nom: "Biais d'attribution", description: "La tendance à attribuer les comportements des autres à des dispositions internes plutôt qu'à des facteurs externes.", emoji: "🧠" },
    { nom: "Biais du survivant", description: "La tendance à se concentrer sur les exemples qui ont réussi tout en négligeant ceux qui ont échoué, car ils ne sont pas aussi visibles.", emoji: "🚀" },
    { nom: "Biais d'engagement", description: "La tendance à s'engager de plus en plus dans une décision ou un projet, même lorsque les preuves indiquent qu'il faut abandonner.", emoji: "🛠️" },
    { nom: "Effet de contraste", description: "La tendance à percevoir les différences entre deux objets ou idées plus fortement lorsqu'ils sont comparés simultanément.", emoji: "⚖️" },
    { nom: "Effet d'entraînement", description: "La tendance à adopter des croyances ou comportements parce qu'un grand nombre de personnes les adoptent déjà.", emoji: "🚂" },
    { nom: "Biais de groupe", description: "La tendance à privilégier les idées et opinions du groupe auquel on appartient, souvent au détriment de la pensée critique.", emoji: "👥" },
    { nom: "Effet de désinformation", description: "La tendance des informations fausses ou trompeuses à interférer avec la mémoire d'événements passés.", emoji: "📰" },
    { nom: "Effet de surconfiance", description: "La tendance à surestimer ses propres capacités, connaissances ou jugement.", emoji: "💪" },
    { nom: "Biais rétrospectif", description: "La tendance à voir les événements passés comme ayant été prévisibles après qu'ils se sont produits.", emoji: "🔮" },
    { nom: "Effet de contexte", description: "La tendance à évaluer une situation en fonction du contexte dans lequel elle se produit plutôt que sur sa base intrinsèque.", emoji: "🏞️" },
    { nom: "Biais de croyance", description: "La tendance à évaluer la force des arguments en fonction de la plausibilité de leur conclusion plutôt que de leur validité logique.", emoji: "💡" },
    { nom: "Effet de surjustification", description: "La tendance à diminuer son intérêt pour une activité lorsqu'elle est récompensée de manière extrinsèque.", emoji: "🏆" },
    { nom: "Biais d'information", description: "La tendance à rechercher plus d'informations que nécessaire pour prendre une décision, souvent au détriment de l'action.", emoji: "📈" },
    { nom: "Effet de la troisième personne", description: "La tendance à croire que les autres sont plus influencés par les médias que soi-même.", emoji: "📺" },
    { nom: "Effet d'ancrage mental", description: "La tendance à être trop influencé par les premières impressions ou les premières informations reçues.", emoji: "🗿" },
    { nom: "Effet de contraste émotionnel", description: "La tendance à percevoir les émotions actuelles de manière plus intense par contraste avec des émotions récentes différentes.", emoji: "🎭" },
    { nom: "Biais d'illusion de contrôle", description: "La tendance à surestimer son contrôle sur des événements qui sont en réalité largement déterminés par le hasard.", emoji: "🎲" },
    { nom: "Effet de mise en conformité sociale", description: "La tendance à adopter les comportements et croyances du groupe pour être accepté.", emoji: "👫" },
    { nom: "Effet placebo", description: "La tendance à ressentir des améliorations en santé suite à la croyance en l'efficacité d'un traitement inactif.", emoji: "💊" },
    { nom: "Effet de Zeigarnik", description: "La tendance à mieux se souvenir des tâches incomplètes que des tâches achevées.", emoji: "🔄" },
    { nom: "Biais d'intentionnalité", description: "La tendance à croire que les événements se produisent pour des raisons spécifiques plutôt que par hasard.", emoji: "🎯" },
    { nom: "Effet de retour de flammes", description: "La tendance à renforcer ses croyances face à des preuves contradictoires.", emoji: "🔥" },
    { nom: "Biais de moralité supérieure", description: "La tendance à se voir comme plus moral que les autres.", emoji: "👼" },
    { nom: "Biais de complaisance", description: "La tendance à attribuer ses succès à soi-même et ses échecs à des facteurs extérieurs.", emoji: "🏅" },
    { nom: "Biais d'excès de confiance", description: "La tendance à surestimer ses connaissances et ses capacités.", emoji: "🌟" },
    { nom: "Effet de l'hypocrisie", description: "La tendance à critiquer chez les autres des comportements que l'on adopte soi-même.", emoji: "🙃" },
    { nom: "Biais de coût irrécupérable", description: "La tendance à poursuivre un investissement à cause des ressources déjà engagées, même si cela ne fait plus de sens.", emoji: "💸" },
    { nom: "Effet de la durée", description: "La tendance à évaluer la qualité d'une expérience basée sur sa durée plutôt que sur son intensité.", emoji: "⌛" },
    { nom: "Biais de projection", description: "La tendance à penser que les autres pensent comme nous.", emoji: "🔍" },
    { nom: "Effet de contraste perceptif", description: "La tendance à percevoir des différences plus importantes entre deux choses quand elles sont présentées simultanément.", emoji: "🔄" },
    { nom: "Effet de paréidolie", description: "La tendance à voir des formes familières dans des motifs aléatoires.", emoji: "🌕" },
    { nom: "Biais de distinction", description: "La tendance à juger deux options plus différemment lorsqu'elles sont évaluées simultanément que lorsqu'elles sont évaluées séparément.", emoji: "📏" },
    { nom: "Biais de responsabilité", description: "La tendance à attribuer la responsabilité des événements à des personnes plutôt qu'à des circonstances externes.", emoji: "👤" },
    { nom: "Effet de vérité illusoire", description: "La tendance à croire qu'une déclaration est vraie si elle est répétée souvent.", emoji: "🔄" },
    { nom: "Biais de compensation morale", description: "La tendance à se permettre de faire quelque chose de mal après avoir fait quelque chose de bien.", emoji: "⚖️" },
    { nom: "Effet de récence disproportionnée", description: "La tendance à accorder trop d'importance aux informations récentes par rapport aux plus anciennes.", emoji: "🕰️" },
    { nom: "Biais d'égocentricité", description: "La tendance à se voir comme plus important dans des événements que l'on ne l'est réellement.", emoji: "💁" },
    { nom: "Effet de regroupement", description: "La tendance à percevoir des modèles dans des séquences aléatoires de données.", emoji: "📈" },
    { nom: "Biais de l'intérêt personnel", description: "La tendance à attribuer ses succès à des facteurs internes et ses échecs à des facteurs externes.", emoji: "🌟" },
    { nom: "Effet de halo négatif", description: "La tendance à laisser une mauvaise impression générale influencer la perception des caractéristiques spécifiques.", emoji: "😈" },
    { nom: "Biais de faux espoir", description: "La tendance à croire que les situations futures seront meilleures malgré des preuves du contraire.", emoji: "🌅" },
    { nom: "Effet d'assimilation de la similarité", description: "La tendance à percevoir les membres d'un groupe externe comme plus similaires entre eux qu'ils ne le sont en réalité.", emoji: "👥" },
    { nom: "Biais d'exposition sélective", description: "La tendance à privilégier les informations qui confirment ses croyances existantes.", emoji: "📚" },
    { nom: "Effet de mise en évidence", description: "La tendance à accorder trop d'importance à une caractéristique ou à un événement en particulier.", emoji: "💡" },
    { nom: "Effet de priming", description: "La tendance à influencer la perception ou la réponse à un stimulus en exposant à un stimulus antérieur.", emoji: "🌱" },
    { nom: "Biais de dissonance cognitive", description: "La tendance à ressentir de l'inconfort face à des informations contradictoires et à chercher à réduire cet inconfort.", emoji: "🤯" },
    { nom: "Effet de polarisation", description: "La tendance à voir des options comme plus extrêmes après les avoir discutées avec un groupe.", emoji: "↔️" },
    { nom: "Effet de victime", description: "La tendance à se voir comme une victime des circonstances plus souvent que nécessaire.", emoji: "😢" },
    { nom: "Biais de familiarité", description: "La tendance à préférer des choses simplement parce qu'elles nous sont familières.", emoji: "🏠" },
    { nom: "Effet de centralité", description: "La tendance à voir les caractéristiques moyennes comme plus représentatives d'un groupe.", emoji: "🎯" },
    { nom: "Effet de dévalorisation", description: "La tendance à diminuer l'importance des succès des autres pour se sentir mieux dans ses propres réalisations.", emoji: "😒" },
    { nom: "Biais de proportionnalité", description: "La tendance à croire que les grandes causes doivent avoir de grandes conséquences et vice versa.", emoji: "⚖️" },
    { nom: "Effet de similarité", description: "La tendance à préférer les gens ou les choses qui sont similaires à soi.", emoji: "👬" },
    { nom: "Biais de soumission à l'autorité", description: "La tendance à suivre les ordres ou les suggestions d'une figure d'autorité.", emoji: "👮" },
    { nom: "Effet de rigidité", description: "La tendance à maintenir ses croyances et ses comportements même face à des preuves contraires.", emoji: "🛡️" },
    { nom: "Biais de négativité", description: "La tendance à accorder plus d'importance aux expériences négatives qu'aux positives.", emoji: "👎" },
    { nom: "Effet de supériorité illusoire", description: "La tendance à se voir comme supérieur à la moyenne dans divers domaines.", emoji: "🌟" },
    { nom: "Effet de mode", description: "La tendance à adopter des comportements ou des croyances populaires pour être à la mode.", emoji: "🎩" },
    { nom: "Biais de réactance", description: "La tendance à réagir de manière opposée à une règle ou une restriction perçue comme une atteinte à sa liberté.", emoji: "🚫" },
    { nom: "Effet de distraction", description: "La tendance à être influencé par des informations non pertinentes lors de la prise de décision.", emoji: "🔊" },
    { nom: "Biais de généralisation abusive", description: "La tendance à tirer des conclusions générales à partir d'un petit nombre d'exemples.", emoji: "📉" },
    { nom: "Effet de promesse", description: "La tendance à accorder plus de valeur à une récompense future plutôt qu'à une immédiate.", emoji: "🔮" },
    { nom: "Biais de supériorité de groupe", description: "La tendance à croire que le groupe auquel on appartient est supérieur aux autres.", emoji: "💪" },
    { nom: "Effet de parité", description: "La tendance à vouloir équilibrer les échanges pour éviter le sentiment d'injustice.", emoji: "⚖️" },
    { nom: "Biais d'influence sociale normative", description: "La tendance à adopter des comportements acceptés par le groupe pour éviter le rejet.", emoji: "👥" },
    { nom: "Effet de choix paradoxal", description: "La tendance à éprouver plus de stress et d'insatisfaction avec un nombre élevé d'options.", emoji: "🔀" },
    { nom: "Biais d'identité", description: "La tendance à protéger ses croyances et ses attitudes qui font partie de son identité personnelle.", emoji: "🆔" },
    { nom: "Effet de mémoire reconstructive", description: "La tendance à reconstruire des souvenirs de manière inexacte à partir de diverses sources d'information.", emoji: "🧠" },
    { nom: "Effet de dépendance au sentier", description: "La tendance à continuer sur une trajectoire prise par habitude, même si une meilleure option est disponible.", emoji: "🛤️" },
    { nom: "Biais de congruence", description: "La tendance à privilégier les informations qui sont en accord avec ses croyances ou hypothèses actuelles.", emoji: "🧩" },
    { nom: "Effet de la responsabilité collective", description: "La tendance à réduire son sentiment de responsabilité lorsque d'autres personnes sont également impliquées.", emoji: "👥" },
    { nom: "Biais de réduction cognitive", description: "La tendance à simplifier une situation complexe en se concentrant sur un nombre limité de facteurs.", emoji: "🔢" },
    { nom: "Effet de contraste séquentiel", description: "La tendance à percevoir une différence plus marquée entre deux stimuli présentés successivement.", emoji: "⏩" },
    { nom: "Effet d'abondance", description: "La tendance à consommer plus lorsque les ressources sont abondantes.", emoji: "🍽️" },
    { nom: "Biais d'assimilation", description: "La tendance à interpréter les nouvelles informations en les intégrant dans ses schémas mentaux existants.", emoji: "🧠" },
    { nom: "Effet de polarisation de groupe", description: "La tendance à adopter des positions plus extrêmes après avoir discuté avec un groupe partageant les mêmes idées.", emoji: "🏞️" },
    { nom: "Biais de non-exclusivité", description: "La tendance à croire que des événements ou des actions sont plus corrélés qu'ils ne le sont réellement.", emoji: "🔗" },
    { nom: "Effet de surpondération des événements récents", description: "La tendance à accorder plus de poids aux événements récents qu'aux événements plus anciens.", emoji: "🗓️" },
    { nom: "Effet de préséance", description: "La tendance à accorder plus d'importance à la première information reçue qu'aux informations suivantes.", emoji: "1️⃣" },
    { nom: "Effet de récupération", description: "La tendance à mieux se souvenir des informations en fonction de la manière dont elles ont été encodées.", emoji: "💾" },
    { nom: "Biais de sympathie", description: "La tendance à être plus facilement persuadé par des personnes que l'on trouve sympathiques.", emoji: "😊" },
    { nom: "Effet de répétition", description: "La tendance à juger une information comme plus véridique lorsqu'elle est répétée.", emoji: "🔄" },
    { nom: "Effet de stéréotype", description: "La tendance à attribuer des caractéristiques spécifiques à une personne en fonction de son appartenance à un groupe.", emoji: "🧑‍🤝‍🧑" },
    { nom: "Biais de préjugé", description: "La tendance à former une opinion sur une personne ou un groupe sans connaître les faits réels.", emoji: "👎" },
    { nom: "Effet de contraste", description: "La tendance à percevoir des différences plus marquées entre deux objets lorsqu'ils sont évalués ensemble.", emoji: "⚖️" },
    { nom: "Biais de complétude", description: "La tendance à croire qu'une action ou une information est complète même lorsqu'elle ne l'est pas.", emoji: "✔️" },
    { nom: "Effet de contagion émotionnelle", description: "La tendance à imiter les émotions des personnes autour de nous.", emoji: "😄" },
    { nom: "Effet de fausse unicité", description: "La tendance à croire que ses propres attributs et opinions sont plus rares qu'ils ne le sont en réalité.", emoji: "🌟" },
    { nom: "Biais de probabilité de base", description: "La tendance à ignorer les probabilités de base lorsque l'on évalue la probabilité d'un événement.", emoji: "📉" },
    { nom: "Effet de confirmation d'hypothèse", description: "La tendance à rechercher des preuves qui confirment une hypothèse plutôt que des preuves qui la réfutent.", emoji: "🔍" },
    { nom: "Effet de contraste perceptuel", description: "La tendance à percevoir une différence plus marquée entre deux stimuli présentés simultanément.", emoji: "🔄" },
    { nom: "Biais d'engagement", description: "La tendance à persister dans une décision ou un comportement malgré des preuves indiquant qu'il est erroné.", emoji: "🔒" },
    { nom: "Effet de polarisation affective", description: "La tendance à ressentir des émotions plus intenses lorsque l'on discute avec des personnes ayant des opinions similaires.", emoji: "💥" },
    { nom: "Effet de la banalisation", description: "La tendance à minimiser l'importance d'un problème ou d'une situation.", emoji: "📉" },
    { nom: "Biais de centration", description: "La tendance à se concentrer sur un seul aspect d'une situation au détriment des autres.", emoji: "🎯" },
    { nom: "Effet de disconfirmation", description: "La tendance à ignorer ou à rejeter les informations qui contredisent ses croyances.", emoji: "🚫" },
    { nom: "Effet de surévaluation de soi", description: "La tendance à se voir comme meilleur que ce que l'on est réellement.", emoji: "🌟" },
    { nom: "Biais d'optimisme irréaliste", description: "La tendance à croire que les événements positifs sont plus probables pour soi-même que pour les autres.", emoji: "🌞" },
    { nom: "Effet de surcompensation", description: "La tendance à réagir de manière excessive pour compenser une faiblesse perçue.", emoji: "⚖️" },
    { nom: "Effet de fausse modestie", description: "La tendance à minimiser ses réussites pour obtenir des compliments ou des louanges.", emoji: "🙇" },
    { nom: "Effet de disqualification", description: "La tendance à rejeter les compliments ou les louanges que l'on reçoit.", emoji: "🙅" },
    { nom: "Effet de préjugé de groupe", description: "La tendance à avoir des opinions biaisées sur un groupe en fonction des stéréotypes.", emoji: "👥" },
    { nom: "Biais de projection des préférences", description: "La tendance à supposer que les autres partagent les mêmes préférences que soi-même.", emoji: "🔄" },
    { nom: "Effet de surpondération des attentes", description: "La tendance à accorder trop d'importance aux attentes plutôt qu'aux faits réels.", emoji: "📈" },
    { nom: "Biais de normalité", description: "La tendance à croire que les événements sont plus normaux qu'ils ne le sont réellement.", emoji: "🛤️" },
    { nom: "Effet de probabilité subjective", description: "La tendance à évaluer la probabilité d'un événement en fonction de ses expériences personnelles plutôt que des statistiques réelles.", emoji: "📊" },
    { nom: "Effet de rigidité cognitive", description: "La tendance à maintenir ses croyances malgré des preuves contraires.", emoji: "🧠" },
    { nom: "Biais de relativité", description: "La tendance à juger la valeur d'une option en la comparant à d'autres plutôt qu'à sa valeur intrinsèque.", emoji: "⚖️" },
    { nom: "Effet de complexité réduite", description: "La tendance à simplifier des situations complexes en les réduisant à des termes simples.", emoji: "🔢" },
    { nom: "Biais de groupe de référence", description: "La tendance à se comparer à un groupe de référence et à adapter ses comportements en conséquence.", emoji: "👥" },
    { nom: "Effet de l'échec anticipé", description: "La tendance à éviter de s'engager dans des tâches de peur de l'échec.", emoji: "🚫" },
    { nom: "Effet de double standard", description: "La tendance à avoir des critères différents pour soi-même et pour les autres.", emoji: "⚖️" },
    { nom: "Biais d'illusion de transparence", description: "La tendance à croire que ses émotions sont plus visibles pour les autres qu'elles ne le sont réellement.", emoji: "🔍" },
    { nom: "Effet de l'importance disproportionnée", description: "La tendance à accorder une importance excessive à certains détails au détriment de l'ensemble.", emoji: "🔍" },
    { nom: "Biais de faux consensus", description: "La tendance à surestimer le degré d'accord des autres avec ses propres opinions.", emoji: "🤝" },
    { nom: "Effet de la mentalité de troupeau", description: "La tendance à suivre les actions ou les croyances d'un groupe sans réflexion critique.", emoji: "🐑" },
    { nom: "Biais de responsabilité diffusion", description: "La tendance à se sentir moins responsable de ses actions lorsqu'elles sont effectuées en groupe.", emoji: "👥" },
    { nom: "Effet de motivation auto-affirmante", description: "La tendance à rechercher des informations qui confirment son image positive de soi.", emoji: "🌟" },
    { nom: "Effet de contraste émotionnel", description: "La tendance à ressentir des émotions plus intenses en présence de contrastes émotionnels.", emoji: "🎭" },
    { nom: "Biais de sur-optimisme", description: "La tendance à être excessivement optimiste quant aux résultats futurs.", emoji: "🌞" },
    { nom: "Effet de la familiarité avec le danger", description: "La tendance à sous-estimer les risques de situations dangereuses en raison de la familiarité.", emoji: "⚠️" },
    { nom: "Biais de négligence de la probabilité", description: "La tendance à ignorer les probabilités lorsque l'on évalue le risque.", emoji: "📉" },
    { nom: "Effet de rigidité émotionnelle", description: "La tendance à maintenir des réponses émotionnelles constantes malgré des changements contextuels.", emoji: "🧠" },
    { nom: "Biais de perception sélective", description: "La tendance à percevoir uniquement les informations qui sont en accord avec ses croyances.", emoji: "👀" },
    { nom: "Effet de polarisation cognitive", description: "La tendance à adopter des positions plus extrêmes après avoir discuté avec un groupe partageant les mêmes idées.", emoji: "↔️" },
    { nom: "Biais de répétition sélective", description: "La tendance à se souvenir et à répéter des informations qui confirment ses croyances.", emoji: "🔄" },
    { nom: "Effet de projection biaisée", description: "La tendance à projeter ses propres biais et préjugés sur les autres.", emoji: "🔍" },
    { nom: "Effet de la mémoire construite", description: "La tendance à reconstruire des souvenirs de manière inexacte à partir de diverses sources d'information.", emoji: "🧠" },
    { nom: "Biais de la perception de l'auto-efficacité", description: "La tendance à surestimer sa capacité à effectuer des tâches avec succès.", emoji: "💪" },
    { nom: "Effet de la montée en généralité", description: "La tendance à généraliser des expériences spécifiques à des conclusions plus larges.", emoji: "🌐" },
    { nom: "Biais d'illusion de contrôle", description: "La tendance à surestimer son contrôle sur des événements qui sont en réalité largement déterminés par le hasard.", emoji: "🎲" },
    { nom: "Effet de la complaisance", description: "La tendance à se conformer aux attentes des autres pour éviter les conflits.", emoji: "🤝" },
    { nom: "Effet de déformation rétrospective", description: "La tendance à revoir ses souvenirs en fonction des nouvelles informations.", emoji: "🔄" },
    { nom: "Biais de l'illusion de connaissance", description: "La tendance à croire que l'on connaît plus que ce que l'on connaît réellement.", emoji: "📚" },
    { nom: "Effet de la fausse expertise", description: "La tendance à surestimer ses connaissances ou compétences dans un domaine.", emoji: "🌟" },
    { nom: "Biais de la double contrainte", description: "La tendance à se sentir piégé entre deux options contradictoires.", emoji: "⚖️" },
    { nom: "Effet de simplification excessive", description: "La tendance à simplifier excessivement des situations complexes en les réduisant à des termes simples.", emoji: "🔢" },
    { nom: "Biais de l'intérêt personnel", description: "La tendance à privilégier ses propres intérêts au détriment de ceux des autres.", emoji: "💼" },
    { nom: "Effet de polarisation comportementale", description: "La tendance à adopter des comportements plus extrêmes après avoir discuté avec un groupe partageant les mêmes idées.", emoji: "↔️" },
    { nom: "Effet de la norme sociale", description: "La tendance à se conformer aux comportements acceptés par le groupe pour éviter le rejet.", emoji: "👥" },
    { nom: "Biais de la perspective temporelle", description: "La tendance à évaluer les événements futurs en fonction de leur proximité temporelle.", emoji: "🕰️" },
    { nom: "Effet de la mémoire épisodique", description: "La tendance à se souvenir des événements personnels de manière plus vivante que des faits généraux.", emoji: "🧠" },
    { nom: "Biais de la perception de l'auto-contrôle", description: "La tendance à surestimer sa capacité à contrôler ses impulsions et ses désirs.", emoji: "💪" },
    { nom: "Effet de la montée en généralité", description: "La tendance à généraliser des expériences spécifiques à des conclusions plus larges.", emoji: "🌐" },
    { nom: "Biais de surjustification", description: "La tendance à attribuer ses actions à des motivations externes plutôt qu'à des motivations internes.", emoji: "🎁" },
    { nom: "Effet de la polarisation affective", description: "La tendance à ressentir des émotions plus intenses en présence de contrastes émotionnels.", emoji: "🎭" },
    { nom: "Biais de la prédisposition", description: "La tendance à percevoir les informations en fonction de ses attentes et croyances préexistantes.", emoji: "🔍" },
    { nom: "Effet de la projection optimiste", description: "La tendance à projeter des résultats positifs dans l'avenir malgré des preuves du contraire.", emoji: "🌅" },
    { nom: "Biais de la perception de l'auto-efficacité", description: "La tendance à surestimer sa capacité à effectuer des tâches avec succès.", emoji: "💪" },
    { nom: "Effet de la complaisance", description: "La tendance à se conformer aux attentes des autres pour éviter les conflits.", emoji: "🤝" },
    { nom: "Effet de déformation rétrospective", description: "La tendance à revoir ses souvenirs en fonction des nouvelles informations.", emoji: "🔄" },
    { nom: "Biais de l'illusion de connaissance", description: "La tendance à croire que l'on connaît plus que ce que l'on connaît réellement.", emoji: "📚" },
    { nom: "Effet de la fausse expertise", description: "La tendance à surestimer ses connaissances ou compétences dans un domaine.", emoji: "🌟" },
    { nom: "Biais de la double contrainte", description: "La tendance à se sentir piégé entre deux options contradictoires.", emoji: "⚖️" },
    { nom: "Effet de simplification excessive", description: "La tendance à simplifier excessivement des situations complexes en les réduisant à des termes simples.", emoji: "🔢" },
    { nom: "Biais de l'intérêt personnel", description: "La tendance à privilégier ses propres intérêts au détriment de ceux des autres.", emoji: "💼" },
    { nom: "Effet de polarisation comportementale", description: "La tendance à adopter des comportements plus extrêmes après avoir discuté avec un groupe partageant les mêmes idées.", emoji: "↔️" },
    { nom: "Effet de la norme sociale", description: "La tendance à se conformer aux comportements acceptés par le groupe pour éviter le rejet.", emoji: "👥" },
    { nom: "Biais de la perspective temporelle", description: "La tendance à évaluer les événements futurs en fonction de leur proximité temporelle.", emoji: "🕰️" },
    { nom: "Effet de la mémoire épisodique", description: "La tendance à se souvenir des événements personnels de manière plus vivante que des faits généraux.", emoji: "🧠" },
    { nom: "Biais de la perception de l'auto-contrôle", description: "La tendance à surestimer sa capacité à contrôler ses impulsions et ses désirs.", emoji: "💪" },
    { nom: "Effet de la montée en généralité", description: "La tendance à généraliser des expériences spécifiques à des conclusions plus larges.", emoji: "🌐" },
    { nom: "Biais de surjustification", description: "La tendance à attribuer ses actions à des motivations externes plutôt qu'à des motivations internes.", emoji: "🎁" },
    { nom: "Effet de la polarisation affective", description: "La tendance à ressentir des émotions plus intenses en présence de contrastes émotionnels.", emoji: "🎭" },
    { nom: "Biais de la prédisposition", description: "La tendance à percevoir les informations en fonction de ses attentes et croyances préexistantes.", emoji: "🔍" },
    { nom: "Effet de la projection optimiste", description: "La tendance à projeter des résultats positifs dans l'avenir malgré des preuves du contraire.", emoji: "🌅" }
];


    const tableau = document.getElementById('biais-table').getElementsByTagName('tbody')[0];

    biaisCognitifs.forEach((biais, index) => {
        const row = tableau.insertRow();
        const cellIndex = row.insertCell(0);
        const cellNom = row.insertCell(1);
        const cellDescription = row.insertCell(2);
        const cellEmoji = row.insertCell(3);

        cellIndex.textContent = index + 1;
        cellNom.textContent = biais.nom;
        cellDescription.textContent = biais.description;
        cellEmoji.textContent = biais.emoji;
    });
});
